create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null default 'ユーザー',created_at timestamptz not null default now());
create table if not exists public.groups(id uuid primary key default gen_random_uuid(),name text not null,emoji text not null default '💑',invite_code text not null unique,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.group_members(group_id uuid not null references public.groups(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'member',created_at timestamptz not null default now(),primary key(group_id,user_id));
create table if not exists public.records(id uuid primary key default gen_random_uuid(),group_id uuid not null references public.groups(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,icon text not null default '🥤',title text not null,amount integer not null check(amount>0),note text,created_at timestamptz not null default now());
create table if not exists public.reactions(id uuid primary key default gen_random_uuid(),record_id uuid not null references public.records(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,type text not null,created_at timestamptz not null default now(),unique(record_id,user_id,type));
create or replace function public.is_group_member(gid uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.group_members where group_id=gid and user_id=auth.uid()); $$;
alter table public.profiles enable row level security;alter table public.groups enable row level security;alter table public.group_members enable row level security;alter table public.records enable row level security;alter table public.reactions enable row level security;
create policy "profiles own read" on public.profiles for select using(id=auth.uid());
create policy "profiles own insert" on public.profiles for insert with check(id=auth.uid());
create policy "profiles own update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "groups read authenticated" on public.groups for select using(auth.uid() is not null);
create policy "groups create own" on public.groups for insert with check(created_by=auth.uid());
create policy "members read" on public.group_members for select using(public.is_group_member(group_id));
create policy "members self join" on public.group_members for insert with check(user_id=auth.uid());
create policy "records member read" on public.records for select using(public.is_group_member(group_id));
create policy "records member insert" on public.records for insert with check(user_id=auth.uid() and public.is_group_member(group_id));
create policy "records owner update" on public.records for update using(user_id=auth.uid()) with check(user_id=auth.uid() and public.is_group_member(group_id));
create policy "records owner delete" on public.records for delete using(user_id=auth.uid());
create policy "reactions member read" on public.reactions for select using(exists(select 1 from public.records r where r.id=record_id and public.is_group_member(r.group_id)));
create policy "reactions own insert" on public.reactions for insert with check(user_id=auth.uid() and exists(select 1 from public.records r where r.id=record_id and public.is_group_member(r.group_id)));
create policy "reactions own delete" on public.reactions for delete using(user_id=auth.uid());
do $$ begin alter publication supabase_realtime add table public.records; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.reactions; exception when duplicate_object then null; end $$;
